### ISSUE TITLE
 dall-e-2  net-gpt-3.5-turbo 这两个免费版测试不可用

### ISSUE THREAD

**Issue by panda-cjh** [popjane/free_chatgpt_api#1]
gpt-3.5-turbo-0125
 gpt-3.5-turbo-1106
 gpt-3.5-turbo
 gpt-3.5-turbo-16k
 net-gpt-3.5-turbo (可联网搜索模型)
 whisper-1
 dall-e-2
 text-开头系列模型，例如：text-davinci        dall-e-2  net-gpt-3.5-turbo 这两个免费版测试不可用为什么，免费版有限制了吗？不是长期支持吗

**Comment by popdo** [comment]
dall-e-2和net-gpt-3.5-turbo 都是支持的。

**Comment by popjane** [comment]
这两模型是支持的
