### ISSUE TITLE
免费版现在不支持gpt-3.5-turbo-instruct的调用了吗？

### ISSUE THREAD

**Issue by xiaobing007** [popjane/free_chatgpt_api#16]
client.completions.create(
    model="gpt-3.5-turbo-instruct",
    prompt="今天天气如何？"
)
openai.NotFoundError: Error code: 404 ..., 'type': 'upstream_error', 'param': '404', 'code': 'bad_response_status_code'}}

**Comment by popjane** [comment]
404错误检查自己的程序代码哦
