### ISSUE TITLE
无法支持https://github.com/AI4Finance-Foundation/FinRobot 

### ISSUE THREAD

**Issue by tegulia** [popjane/free_chatgpt_api#17]
按照config说明设置base_url，但是FinRobot 调用openai时仍然报错。  
  {
        "model": "gpt-3.5-turbo",
        "api_key": "sk-XXX",
"base_url":"https://free.gpt.ge/v1/"
    }

// Please modify the content, remove these four lines of comment and rename this file to OAI_CONFIG_LIST to run the sample code.
// If using pyautogen v0.1.x with Azure OpenAI, please replace "base_url" with "api_base" (line 13 and line 20 below). Use "pip list" to check version of pyautogen installed.
//
// NOTE: This configuration lists GPT-4 as the default model, as this represents our current recommendation, and is known to work well with AutoGen. If you use a model other than GPT-4, you may need to revise various system prompts (especially if using weaker models like GPT-3.5-turbo). Moreover, if you use models other than those hosted by OpenAI or Azure, you may incur additional risks related to alignment and safety. Proceed with caution if updating this default.
[
    {
        "model": "gpt-4-0125-preview",
        "api_key": "<your OpenAI API key here>"
    },
    {
        "model": "gpt-4-1106-vision-preview",
        "api_key": "<your OpenAI API key here>"
    },
    {
        "model": "<your Azure OpenAI deployment name>",
        "api_key": "<your Azure OpenAI API key here>",
        "base_url": "<your Azure OpenAI API base here>",
        "api_type": "azure",
        "api_version": "2024-02-15-preview"
    },
    {
        "model": "<your Azure OpenAI deployment name>",
        "api_key": "<your Azure OpenAI API key here>",
        "base_url": "<your Azure OpenAI API base here>",
        "api_type": "azure",
        "api_version": "2024-02-15-preview"
    }
]

---------------------------------------------------------------------------
BadRequestError                           Traceback (most recent call last)
Cell In[5], line 9
      1 company = "NVDA"
      3 assitant = SingleAssistant(
      4     "Market_Analyst",
      5     llm_config,
      6     # set to "ALWAYS" if you want to chat instead of simply receiving the prediciton
      7     human_input_mode="NEVER",
      8 )
----> 9 assitant.chat(
     10     f"Use all the tools provided to retrieve information available for {company} upon {get_current_date()}. Analyze the positive developments and potential concerns of {company} "
     11     "with 2-4 most important factors respectively and keep them concise. Most factors should be inferred from company related news. "
     12     f"Then make a rough prediction (e.g. up/down by 2-3%) of the {company} stock price movement for next week. Provide a summary analysis to support your prediction."
     13 )

File ~/FinRobot/finrobot/agents/workflow.py:154, in SingleAssistant.chat(self, message, use_cache, **kwargs)
    152 def chat(self, message: str, use_cache=False, **kwargs):
    153     with Cache.disk() as cache:
--> 154         self.user_proxy.initiate_chat(
    155             self.assistant,
    156             message=message,
    157             cache=cache if use_cache else None,
    158             **kwargs,
    159         )
    161     print("Current chat finished. Resetting agents ...")
    162     self.reset()

File ~/anaconda3/envs/finrobot/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:1018, in ConversableAgent.initiate_chat(self, recipient, clear_history, silent, cache, max_turns, summary_method, summary_args, message, **kwargs)
   1016     else:
   1017         msg2send = self.generate_init_message(message, **kwargs)
-> 1018     self.send(msg2send, recipient, silent=silent)
   1019 summary = self._summarize_chat(
   1020     summary_method,
   1021     summary_args,
   1022     recipient,
   1023     cache=cache,
   1024 )
   1025 for agent in [self, recipient]:

File ~/anaconda3/envs/finrobot/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:655, in ConversableAgent.send(self, message, recipient, request_reply, silent)
    653 valid = self._append_oai_message(message, "assistant", recipient)
    654 if valid:
--> 655     recipient.receive(message, self, request_reply, silent)
    656 else:
    657     raise ValueError(
    658         "Message can't be converted into a valid ChatCompletion message. Either content or function_call must be provided."
    659     )

File ~/anaconda3/envs/finrobot/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:818, in ConversableAgent.receive(self, message, sender, request_reply, silent)
    816 if request_reply is False or request_reply is None and self.reply_at_receive[sender] is False:
    817     return
--> 818 reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
    819 if reply is not None:
    820     self.send(reply, sender, silent=silent)

File ~/anaconda3/envs/finrobot/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:1972, in ConversableAgent.generate_reply(self, messages, sender, **kwargs)
   1970     continue
   1971 if self._match_trigger(reply_func_tuple["trigger"], sender):
-> 1972     final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
   1973     if logging_enabled():
   1974         log_event(
   1975             self,
   1976             "reply_func_executed",
   (...)
   1980             reply=reply,
   1981         )

File ~/anaconda3/envs/finrobot/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:1340, in ConversableAgent.generate_oai_reply(self, messages, sender, config)
   1338 if messages is None:
   1339     messages = self._oai_messages[sender]
-> 1340 extracted_response = self._generate_oai_reply_from_client(
   1341     client, self._oai_system_message + messages, self.client_cache
   1342 )
   1343 return (False, None) if extracted_response is None else (True, extracted_response)

File ~/anaconda3/envs/finrobot/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:1359, in ConversableAgent._generate_oai_reply_from_client(self, llm_client, messages, cache)
   1356         all_messages.append(message)
   1358 # TODO: #1143 handle token limit exceeded error
-> 1359 response = llm_client.create(
   1360     context=messages[-1].pop("context", None), messages=all_messages, cache=cache, agent=self
   1361 )
   1362 extracted_response = llm_client.extract_text_or_completion_object(response)[0]
   1364 if extracted_response is None:

File ~/anaconda3/envs/finrobot/lib/python3.10/site-packages/autogen/oai/client.py:722, in OpenAIWrapper.create(self, **config)
    720 try:
    721     request_ts = get_current_ts()
--> 722     response = client.create(params)
    723 except APITimeoutError as err:
    724     logger.debug(f"config {i} timed out", exc_info=True)

File ~/anaconda3/envs/finrobot/lib/python3.10/site-packages/autogen/oai/client.py:320, in OpenAIClient.create(self, params)
    318     params = params.copy()
    319     params["stream"] = False
--> 320     response = completions.create(**params)
    322 return response

File ~/anaconda3/envs/finrobot/lib/python3.10/site-packages/openai/_utils/_utils.py:277, in required_args.<locals>.inner.<locals>.wrapper(*args, **kwargs)
    275             msg = f"Missing required argument: {quote(missing[0])}"
    276     raise TypeError(msg)
--> 277 return func(*args, **kwargs)

File ~/anaconda3/envs/finrobot/lib/python3.10/site-packages/openai/resources/chat/completions.py:643, in Completions.create(self, messages, model, frequency_penalty, function_call, functions, logit_bias, logprobs, max_tokens, n, parallel_tool_calls, presence_penalty, response_format, seed, service_tier, stop, stream, stream_options, temperature, tool_choice, tools, top_logprobs, top_p, user, extra_headers, extra_query, extra_body, timeout)
    609 @required_args(["messages", "model"], ["messages", "model", "stream"])
    610 def create(
    611     self,
   (...)
    641     timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN,
    642 ) -> ChatCompletion | Stream[ChatCompletionChunk]:
--> 643     return self._post(
    644         "/chat/completions",
    645         body=maybe_transform(
    646             {
    647                 "messages": messages,
    648                 "model": model,
    649                 "frequency_penalty": frequency_penalty,
    650                 "function_call": function_call,
    651                 "functions": functions,
    652                 "logit_bias": logit_bias,
    653                 "logprobs": logprobs,
    654                 "max_tokens": max_tokens,
    655                 "n": n,
    656                 "parallel_tool_calls": parallel_tool_calls,
    657                 "presence_penalty": presence_penalty,
    658                 "response_format": response_format,
    659                 "seed": seed,
    660                 "service_tier": service_tier,
    661                 "stop": stop,
    662                 "stream": stream,
    663                 "stream_options": stream_options,
    664                 "temperature": temperature,
    665                 "tool_choice": tool_choice,
    666                 "tools": tools,
    667                 "top_logprobs": top_logprobs,
    668                 "top_p": top_p,
    669                 "user": user,
    670             },
    671             completion_create_params.CompletionCreateParams,
    672         ),
    673         options=make_request_options(
    674             extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
    675         ),
    676         cast_to=ChatCompletion,
    677         stream=stream or False,
    678         stream_cls=Stream[ChatCompletionChunk],
    679     )

File ~/anaconda3/envs/finrobot/lib/python3.10/site-packages/openai/_base_client.py:1266, in SyncAPIClient.post(self, path, cast_to, body, options, files, stream, stream_cls)
   1252 def post(
   1253     self,
   1254     path: str,
   (...)
   1261     stream_cls: type[_StreamT] | None = None,
   1262 ) -> ResponseT | _StreamT:
   1263     opts = FinalRequestOptions.construct(
   1264         method="post", url=path, json_data=body, files=to_httpx_files(files), **options
   1265     )
-> 1266     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))

File ~/anaconda3/envs/finrobot/lib/python3.10/site-packages/openai/_base_client.py:942, in SyncAPIClient.request(self, cast_to, options, remaining_retries, stream, stream_cls)
    933 def request(
    934     self,
    935     cast_to: Type[ResponseT],
   (...)
    940     stream_cls: type[_StreamT] | None = None,
    941 ) -> ResponseT | _StreamT:
--> 942     return self._request(
    943         cast_to=cast_to,
    944         options=options,
    945         stream=stream,
    946         stream_cls=stream_cls,
    947         remaining_retries=remaining_retries,
    948     )

File ~/anaconda3/envs/finrobot/lib/python3.10/site-packages/openai/_base_client.py:1046, in SyncAPIClient._request(self, cast_to, options, remaining_retries, stream, stream_cls)
   1043         err.response.read()
   1045     log.debug("Re-raising status error")
-> 1046     raise self._make_status_error_from_response(err.response) from None
   1048 return self._process_response(
   1049     cast_to=cast_to,
   1050     options=options,
   (...)
   1053     stream_cls=stream_cls,
   1054 )

BadRequestError: Error code: 400 - {'error': {'message': "Invalid schema for function 'get_basic_financials': '' is not valid under any of the given schemas. (request id: 20240713045013142821554u0vSN76O) (request id: 2024071312501312836628874444917)", 'type': 'invalid_request_error', 'param': '', 'code': None}}

**Comment by popjane** [comment]
免费key不支持GPT4
