### ISSUE TITLE
无法进行请求

### ISSUE THREAD

**Issue by NetError5000** [popjane/free_chatgpt_api#18]
我使用chatgpt-next-web进行免费的kay请求，但是返回结果是
{
  "error": true,
  "message": "Failed to fetch"
}

我该如何解决？

**Comment by kxggit** [comment]
我也遇到过同样的情况，但是检查后发现是接口地址从https://free.gpt.ge写成了http://free.gpt.ge，你可以检查一下是不是这个问题

**Comment by HongShi2333** [comment]
我使用next chat重新进行了请求，但似乎行不通……

**Comment by cherry520025** [comment]
openai.error.PermissionError: Country, region, or territory not supported

**Comment by popjane** [comment]
接口地址填错 才会出现Failed to fetch
