### ISSUE TITLE
gpt-4o-mini无可用渠道

### ISSUE THREAD

**Issue by NetError5000** [popjane/free_chatgpt_api#22]
我使用申请的免费的API调用GPT-4o-mini，返回结果如下
```
{
  "error": {
    "message": "当前分组 default 下对于模型 gpt-4o-mini 无可用渠道 (request id: 2024080513015045025767240621551)",
    "type": "v_api_error"
  }
}
```
请问是免费API不支持GPT-4o-mini模型了吗？

**Comment by HongShi2333** [comment]
我于今天下午也遇到了相同的情况

**Comment by popdo** [comment]
已修复了

**Comment by mgsray** [comment]
同问，是什么问题？

**Comment by popjane** [comment]
应该是可以正常访问了，这个模型我们偶尔会故障，程序10分钟内会自启动

**Comment by HongShi2333** [comment]
感谢，8/5晚间已经能够正常调用了

**Comment by mgsray** [comment]
今天又发生了，持续时间远超10分钟

**Comment by popjane** [comment]
已恢复

**Comment by MINGRUI001** [comment]
4o-mini好像现在又出问题了…感觉持续两天了

**Comment by zaizhe** [comment]
> 已恢复

现在已经好几天用不了了
{
  "error": {
    "message": "当前分组 default 下对于模型 gpt-4o-mini-2024-07-18 无可用渠道 (request id: 2024092909401611808867076996418)",
    "type": "v_api_error"
  }
}
