### ISSUE TITLE
客服加不上

### ISSUE THREAD

**Issue by CharlesPikachu** [popjane/free_chatgpt_api#24]
你好，我想买gpt-4o-mini的接口服务，想先咨询一下，但是客服一直加不上，是否可以提供一下其他的联系方式？

**Comment by CharlesPikachu** [comment]
我加了很多次，一直没通过

**Comment by popjane** [comment]
你加群啊。网站直接下单就好了

**Comment by CharlesPikachu** [comment]
加群要先下单，我没看到有mini单独的下单链接，不确定我下单4的话价格咋算，mini 每1M token的价格应该不一样啊。我要处理的数据量大。比较care价格问题，想先找客服问问的本来

**Comment by popjane** [comment]
充值所有GPT模型都可以用，没有什么mini的说法
