### ISSUE TITLE
无法调用，用户配额不足

### ISSUE THREAD

**Issue by gxlydlyf** [popjane/free_chatgpt_api#26]
API Error: Status Code 403, {"error":{"message":"user quota is not enough (request id: 2024081922011112714735330169131)","type":"v_api_error","param":"","code":"insufficient_user_quota"}}
模型gpt-3.5-turbo-16k
![image](https://github.com/user-attachments/assets/5e2f7598-dc2f-4189-895d-5741e878776c)

**Comment by buzaiqizhong** [comment]
也遇到了相同的问题和报错，期待一个解答

**Comment by SRInternet** [comment]
我也遇到了相同的问题，希望能快速获得答复
