### ISSUE TITLE
 Incorrect API key provided

### ISSUE THREAD

**Issue by Cuirundi** [popjane/free_chatgpt_api#3]
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-PMafP***************************************E873. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}出现了这个问题

**Comment by popjane** [comment]
需要打开api地址使用。项目中有介绍
