### ISSUE TITLE
沉浸式翻译添加OPEN AI 的API KEY和API URL无法使用。

### ISSUE THREAD

**Issue by hz923** [popjane/free_chatgpt_api#41]
在沉浸式翻译设置=》翻译服务=》OPEN AI设置=》中添加了自定义 API Key和自定义 API 接口地址：https://free.gpt.ge 后=》[点此测试服务]提示，“Network request failed”

**Comment by popjane** [comment]
域名被墙，已经修改api接口地址

**Comment by Little-Stars520** [comment]
@popjane popjane现在用了新的api接口地址也出现了“Network request failed”，请问怎么解决
