### ISSUE TITLE
多模态任务

### ISSUE THREAD

**Issue by ingenieur-zhang** [popjane/free_chatgpt_api#48]
我写了一个脚本用免费的key运行一个多模态任务（图像+文字），然后总是得到这样的输出：
INFO:httpx:HTTP Request: POST https://free.v36.cm/chat/completions "HTTP/1.1 200 OK"
打开链接是：请前往 [Github项目](https://github.com/popjane/free_chatgpt_api) 中进行免费授权，或支持 [付费项目](https://api.gpt.ge/)！
这是为什么？

**Comment by popjane** [comment]
请求地址错误，缺少v1，正确的是

```
https://free.v36.cm/v1/chat/completions
```
