### ISSUE TITLE
是不是已经失效了

### ISSUE THREAD

**Issue by yaojiwei520** [popjane/free_chatgpt_api#52]
遇到了来自 OpenAI API 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

API Error: Status Code 503, {"error":{"message":"当前分组 default 下对于模型 gpt-4o-mini 无可用渠道 (request id: 2024112820563022750245817097590)","type":"v_api_error"}}

**Comment by popjane** [comment]
最近存在大量机器号恶意批量注册请求行为，某些恶意用户甚至批量申请数百个key，造成库存消耗过快，使得部分模型出现不可用状态，我们会定期检查模型库存并补充。

**为了保证免费服务可持续性，我们将会严格封禁所有重复注册账户，并限制并发数量。**

超过个人用户**正常请求频率**将会被系统拦截，并限制请求1～5分钟，如有高并发场景，请使用我们的付费API（极速无并发限制）。

**免费API服务我们会持续维护，也请大家爱惜资源，不要滥用！**

感谢大家的理解与支持！
