### ISSUE TITLE
连接失败（Connection Error）

### ISSUE THREAD

**Issue by CopperFirst1** [popjane/free_chatgpt_api#53]
用的是免费版，不管使用gpt-4o-mini还是3.5，跑了一段时间文本对话，就会报错。不知道是不是免费版有token次数限制？还是服务器崩了。求教该怎么办？

**Comment by popjane** [comment]
最近存在大量机器号恶意批量注册请求行为，某些恶意用户甚至批量申请数百个key，造成库存消耗过快，使得部分模型出现不可用状态，我们会定期检查模型库存并补充。

**为了保证免费服务可持续性，我们将会严格封禁所有重复注册账户，并限制并发数量。**

超过个人用户**正常请求频率**将会被系统拦截，并限制请求1～5分钟，如有高并发场景，请使用我们的付费API（极速无并发限制）。

**免费API服务我们会持续维护，也请大家爱惜资源，不要滥用！**

感谢大家的理解与支持！

**Comment by popjane** [comment]
#51
